### ISSUE TITLE
Project Tasks

### ISSUE THREAD

**Issue by tiagomenegaz** [tmmgarcia/content-parser#1]
_I wrote down this issue to keep the development on track_

- Project Structure

- [x] create rails base structure #2
- [x] add [rspec](http://rspec.info/)  #3
- [x] update tests with [rspec-rails](https://github.com/rspec/rspec-rails) #4

Database
- [x] plan basic database

```
{
  page: {
    original_url: { type: str }
  },
  content: {
    page_id: { type: int }
    value: { type: str },
    kind: { enum: [h1, h2, h3, str] }
  }
}
```

- [x] implement database #5 #6

Endpoints
It's required to use [jsonapi-resources](https://github.com/cerebris/jsonapi-resources) to handle all responses.

- [x] create post endpoint #7
- [x] create get endpoint #7
```
{
   data: [{
      id: "x"
   }]
}
```

Requirements
- [x] add [Server Requirements](https://jsonapi.org/format/#content-negotiation-servers) from JSON API #7
- [x] add content parser #9 

Improvements
- [x] update README with request instructions #8
- [x] fix broken specs #10
- [x] add format validator to `original_url` #11
- [x] add docker environment #12 #13
